### ISSUE TITLE
jcenter replacement / publish to Maven Central?

### ISSUE THREAD

**Issue by smirceal** [Vantiv/cnp-sdk-for-java#24]
Hello there,

JCenter is going away: https://blog.gradle.org/jcenter-shutdown
What's your plan for future release on publishing the jars? 
Also, is it possible to get the latest version(s) pushed to MavenCentral so that we don't have to take a dependency on jcenter?

Thanks,
Mircea

**Comment by vishal4393** [comment]
As JCenter is going away and there is no support for new package versions, we are planning to push the latest version of the SDK to MavenCentral by around mid September 2021.

**Comment by smirceal** [comment]
@vishal4393 thanks for the update. Any chance we could push the current version to Maven Central now-ish? 
Thank you

**Comment by mishravinod202** [comment]
@smirceal - Migration to maven will require some package changes at our end. We have planned to push current version to maven central by September 2021.

Hope this help.

**Comment by smirceal** [comment]
sure thing. We are trying to avoid using jcenter alltogether.

Here is something that might help: 
https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/

Thanks!

**Comment by ab9967** [comment]
@smirceal We have published new version to [mavenCentral](https://mvnrepository.com/artifact/io.github.vantiv/cnp-sdk-for-java) and is available to be used.
version : 12.19.1
