### ISSUE TITLE
Multiple jaxb-core dependencies in version 12.37.2_17

### ISSUE THREAD

**Issue by jenssuhr** [Vantiv/cnp-sdk-for-java#66]
Hello,
version 12.37.2_17 contains two `jaxb-core` dependencies with different groups (`com.sun.xml.bind` and `org.glassfish.jaxb`, https://github.com/Vantiv/cnp-sdk-for-java/blob/12.37.2_17/build.gradle#L59). This causes the following Gradle error in the `installDist` task after updating the SDK version:
```Entry lib/jaxb-core-4.0.5.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.9/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.```
Are the duplicate dependencies intended?

**Comment by Nitinsl** [comment]
Hello, 
Thanks for informing us about this issue. Since we are using older Gradle version we didn't see this issue at our end.
Fix to remove duplicate Jaxb-core dependency is in progress. And we will update you once we release new version with this fix.

**Comment by Nitinsl** [comment]
Hello, 
The issue with duplicate Jaxb-core dependency has been resolved and we have released new version of Java SDK i.e.
cnp-sdk-for-java-12.37.4_17

**Comment by jenssuhr** [comment]
Hi,
thank you for the update. I can confirm that the issue has been solved with version 12.37.4_17.
